name: Build-APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: Luka-H0/buildozer-action@v0
        with:
          command: buildozer android debug
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: app-package
          path: bin/*.apk
