name: Final-Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Buildozer
        uses: Luka-H0/buildozer-action@v0
        with:
          command: buildozer android debug
      - name: Save
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: bin/*.apk
          
