name: Build-App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: Luka-H0/buildozer-action@v0
        with:
          command: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-android-app
          path: bin/*.apk
          
