name: Build
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Luka-H0/buildozer-action@v0
        with:
          command: buildozer android debug
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: bin/*.apk
          
